### ISSUE TITLE
Test de Donovan done :

### ISSUE THREAD

**Issue by aschoenh** [pscott/42sh#176]

**Comment by aschoenh** [comment]
Misc : DONE
mini pb : on ne set pas SHLVL = 1 quand on unsetenv SHLVL, bash le fait.

**Comment by Mporzier** [comment]
DONE 

- Misc
- List
- Builtins
- Simple commands
- And Or
- Builtin exit
- Builtin env
- Builtin echo
- Pipe 
- Builtin cd (fixed something, almost sure everything is okay)
- Builtin setenv
- Builtin unsetenv
- redirection

remains : 

 NONE

**Comment by Neurochirurgie** [comment]
Builtins : done

**Comment by Neurochirurgie** [comment]
Simple commands : done

**Comment by aschoenh** [comment]
Builtins exit : in process

**Comment by aschoenh** [comment]
And Or : DONE

**Comment by Neurochirurgie** [comment]
Done : builtin_env
