### ISSUE TITLE
set variables problems and errors

### ISSUE THREAD

**Issue by pscott** [pscott/42sh#185]
```toto=${ }```

**Comment by Neurochirurgie** [comment]
"a="
"echo $((a))"

I am updating the a variable tho i shouldn't

**Comment by Neurochirurgie** [comment]
"a=prout"
"echo $((a++))"

A has been set to 1, it erased its content

**Comment by Mporzier** [comment]
Parse in arith expansion the variables given, I can reject a variable if it isn't well set

{Seems to be working ?}

**Comment by Neurochirurgie** [comment]
Export -p not done, does the same as export without arg

I did not understand yet how does "export -p" work when there are args after the flag

**Comment by Mporzier** [comment]
ERROR FOR VARIABLES ASSIGNATION

x=$((1+1))

x has to be set to 2 instead of the litteral string (FOR ENZO)

**Comment by Mporzier** [comment]
"a=hello b=world; b=42 echo prout "
"prout=prout"

b is now "42" instead of "world", the saved shell variables badly updates the current shell variables
