### ISSUE TITLE
Errors auto-completion

### ISSUE THREAD

**Issue by Mporzier** [pscott/42sh#202]
Builtins missing : set / unset / history / export

**Comment by aschoenh** [comment]
OK  ; juste, se souvenir de rm le builtin history (pas demandé dans le sujet, je l'ai pas mis dans la completion)

**Comment by Mporzier** [comment]
List of done builtins, for auto completion when PATH is unset : 
- exit
- cd
- echo
- hash
- test
- type
- export
- unset
- set
- jobs
- fg
- bg
- fc

**Comment by Mporzier** [comment]
Unset PATH ;
No builtins are shown with auto-completion

**Comment by aschoenh** [comment]
fix by 136fd102716619ebf52532f6a884ac2fc37ce866
