### ISSUE TITLE
42ShellTester / Redirections whit no_exist_file

### ISSUE THREAD

**Issue by aschoenh** [pscott/42sh#57]
21sh/redirections/inputs/005-no-such-file (FAILED)

 Description:
 The purpose of this test is to check that using a wrong path within the STDIN redirection `<` results in an error.

 Before test:
 01: rm -f “./no_such_file”

 STDIN:
 01: ./read_on_stdin <no_such_file

 STDOUT:
 SUCCESS    expected_to be_empty
 (no output)

 STDERR:
 SUCCESS    expected_to_not be_empty
 SUCCESS    might match_regex `[Nn]o such file or directory`
 01: 42sh: no_such_file: No such file or directory

 MISC:
 FAILURE    expected_to_not exit_with_status `0`

link : https://github.com/we-sh/42ShellTester/blob/master/spec/21sh/redirections/inputs/005-no-such-file

**Comment by pscott** [comment]
Should be fixed by https://github.com/pscott/42sh/commit/77e308bd37ddec31966194ac9f9909aec38f786e
